# Configuration file for Ae4oSpace
# https://github.com/nikitabobko/AeroSpace
start-at-login = true

after-login-command = []
after-startup-command = ['exec-and-forget sketchybar',  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0']
on-focused-monitor-changed = ['move-mouse window-lazy-center']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c', 'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE' ]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 16
inner.vertical =   16
outer.left =       30
outer.bottom =     30
outer.top =        30
outer.right =      30

[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

alt-1 = 'workspace M1'
alt-2 = 'workspace M2'
alt-3 = 'workspace M3'
alt-4 = 'workspace M4'
alt-5 = 'workspace M5'
alt-q = 'workspace SQ'
alt-w = 'workspace SW'
alt-e = 'workspace SE'

alt-p = ['focus-monitor main', 'workspace prev --wrap-around']
alt-n = ['focus-monitor main', 'workspace next --wrap-around']
alt-shift-p = ['focus-monitor secondary', 'workspace prev --wrap-around']
alt-shift-n = ['focus-monitor secondary', 'workspace next --wrap-around']


alt-shift-1 = 'move-node-to-workspace M1'
alt-shift-2 = 'move-node-to-workspace M2'
alt-shift-3 = 'move-node-to-workspace M3'
alt-shift-4 = 'move-node-to-workspace M4'
alt-shift-5 = 'move-node-to-workspace M5'
alt-shift-q = 'move-node-to-workspace SQ'
alt-shift-w = 'move-node-to-workspace SW'
alt-shift-e = 'move-node-to-workspace SE'



alt-x = 'workspace-back-and-forth'
alt-f = 'layout floating tiling'
alt-shift-f = 'fullscreen'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'


# FOCUS
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# MOVE
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# MODES
alt-shift-r = 'mode resize'
alt-shift-slash = 'mode service'

# LAYOUT
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# BINDING MODES - RESIZE
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
b = 'balance-sizes'

minus = 'resize smart -50'
equal = 'resize smart +50'

enter = 'mode main'
esc = 'mode main'


# BINDING MODES - SERVICE
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
M1 = 'main'                      
M2 = 'main'                      
M3 = 'main'                      
M4 = 'main'
M5 = 'main'
SQ = 'secondary'                 
SW = 'secondary'                 
SE = 'secondary'

# HOOKS
# Make all windows float default

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = "move-node-to-workspace M1"

# [[on-window-detected]]
# if.app-id = 'com.microsoft.VSCode'
# run = "move-node-to-workspace M2"

[[on-window-detected]]
if.app-id='com.todesktop.230313mzl4w4u92'
run = "move-node-to-workspace M2"

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace M3"


[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram' 
run = "move-node-to-workspace SW"
[[on-window-detected]]
if.app-id = 'com.spotify.client' 
run = "move-node-to-workspace SE"

[[on-window-detected]]
if.app-id = 'com.atlassian.trello'
run = "move-node-to-workspace SQ"

# [[on-window-detected]]
# if.app-name-regex-substring = 'Signal|Discord|Messages'
# run = ['layout tiling', 'move-node-to-workspace 5']

[[on-window-detected]]
check-further-callbacks = true
run = 'layout floating'

